name: PR

on:
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    container: node:20-bookworm
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup tzdata
        run: apt-get update -y && apt-get upgrade -y && apt-get install -y tzdata

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: npx eslint --ignore-path .gitignore .

      - name: Formatting
        run:  npx prettier --check **/*.{ts,astro,json,cjs,mjs}

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test
        env:
          TZ: Asia/Jakarta

      - uses: codecov/codecov-action@v3